# Generated by Django 4.1 on 2023-04-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=200, null=True)),
                ('calorie', models.FloatField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
