# Generated by Django 4.1 on 2023-04-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_name', models.CharField(blank=True, max_length=200, null=True)),
                ('calorie', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='food',
            name='calorie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
